# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

language: node_js
node_js:
  - 'stable'
cache:
  directories:
  - node_modules
install:
  - npm prune && npm install

deploy:
  skip_cleanup: true
  provider: script
  script: npm run publish
  on:
    branch: source
