# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

language: node_js
node_js:
  - 'stable'
cache:
  directories:
  - node_modules
install:
  - npm prune
  - npm install

before_deploy:
  - openssl aes-256-cbc -K $encrypted_707f5d2087de_key -iv $encrypted_707f5d2087de_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
  - chmod 600 .travis/deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add .travis/deploy_key
  - git remote add deploy git@github.com:nucleate/nucleate.github.io.git
deploy:
  skip_cleanup: true
  provider: script
  script: npm run publish -- --remote deploy
  on:
    branch: source
